  <script type="application/javascript" src="chrome://bluegriffon/content/utils/dgid.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/global.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/urls.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/notifiers.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/l10n.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/prompter.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/editorUtils.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/css.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/fileUtils.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/bluegriffon.js"/>
  <script type="application/javascript" src="chrome://global/content/globalOverlay.js"/>
  <script type="application/javascript" src="chrome://global/content/nsDragAndDrop.js"/>
  <script type="application/javascript" src="chrome://global/content/nsTransferable.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/customize.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/commands.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/colourPickerHelper.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/activeSourceView.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/zoomManager.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/recentPages.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/toolbars.js"/>

  <script type="application/javascript" src="chrome://diavolo/content/tokeniser.js"/>
  <script type="application/javascript" src="chrome://diavolo/content/highlighter.js"/>
  <script type="application/javascript" src="chrome://diavolo/content/editor.js"/>
  <script type="application/javascript" src="chrome://diavolo/content/grammar.js"/>
  <script type="application/javascript" src="chrome://diavolo/content/selector.js"/>
  <script type="application/javascript" src="chrome://diavolo/content/codecompletion.js"/>
  
  <script type="application/x-javascript" src="chrome://inspector/content/hooks.js"/>
  